# Generated by Django 2.2.28 on 2023-07-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rty', models.CharField(max_length=20)),
                ('sda', models.BigIntegerField(blank=True, null=True)),
                ('fvxv', models.BigIntegerField(blank=True, null=True)),
                ('rel_user_1_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ert_rel_user_1_n', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TYUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjk', models.DecimalField(decimal_places=10, max_digits=30)),
                ('rel_ert_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyui_rel_ert_1_1', to='home.ERT')),
            ],
        ),
    ]
